# coding: utf-8

"""
    AIOZ-AI-PLATFORM API

    API for AIOZ AI Platform

    The version of the OpenAPI document: 1.0
    Contact: support@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from aioz_api_client.models.models_api_key_package import ModelsApiKeyPackage
from typing import Optional, Set
from typing_extensions import Self

class ResponseGetApiKeyPermissionData(BaseModel):
    """
    ResponseGetApiKeyPermissionData
    """ # noqa: E501
    api_key_packages: Optional[List[ModelsApiKeyPackage]] = None
    limit_models: Optional[StrictBool] = None
    models: Optional[List[StrictStr]] = None
    __properties: ClassVar[List[str]] = ["api_key_packages", "limit_models", "models"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ResponseGetApiKeyPermissionData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in api_key_packages (list)
        _items = []
        if self.api_key_packages:
            for _item_api_key_packages in self.api_key_packages:
                if _item_api_key_packages:
                    _items.append(_item_api_key_packages.to_dict())
            _dict['api_key_packages'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ResponseGetApiKeyPermissionData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "api_key_packages": [ModelsApiKeyPackage.from_dict(_item) for _item in obj["api_key_packages"]] if obj.get("api_key_packages") is not None else None,
            "limit_models": obj.get("limit_models"),
            "models": obj.get("models")
        })
        return _obj


