# coding: utf-8

"""
    AIOZ-AI-PLATFORM API

    API for AIOZ AI Platform

    The version of the OpenAPI document: 1.0
    Contact: support@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aioz_api_client.models.response_api_key_history_list_response import ResponseApiKeyHistoryListResponse

class TestResponseApiKeyHistoryListResponse(unittest.TestCase):
    """ResponseApiKeyHistoryListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseApiKeyHistoryListResponse:
        """Test ResponseApiKeyHistoryListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseApiKeyHistoryListResponse`
        """
        model = ResponseApiKeyHistoryListResponse()
        if include_optional:
            return ResponseApiKeyHistoryListResponse(
                data = aioz_api_client.models.response/api_key_history_list_data.response.ApiKeyHistoryListData(
                    records = [
                        aioz_api_client.models.models/api_key_histories.models.ApiKeyHistories(
                            created_at = '', 
                            model_id = '', 
                            status = '', 
                            task_id = '', 
                            updated_at = '', )
                        ], 
                    total = 56, ),
                message = '',
                status = 'success'
            )
        else:
            return ResponseApiKeyHistoryListResponse(
        )
        """

    def testResponseApiKeyHistoryListResponse(self):
        """Test ResponseApiKeyHistoryListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
