# coding: utf-8

"""
    AIOZ-AI-PLATFORM API

    API for AIOZ AI Platform

    The version of the OpenAPI document: 1.0
    Contact: support@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aioz_api_client.models.response_check_model_is_serving_response import ResponseCheckModelIsServingResponse

class TestResponseCheckModelIsServingResponse(unittest.TestCase):
    """ResponseCheckModelIsServingResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseCheckModelIsServingResponse:
        """Test ResponseCheckModelIsServingResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseCheckModelIsServingResponse`
        """
        model = ResponseCheckModelIsServingResponse()
        if include_optional:
            return ResponseCheckModelIsServingResponse(
                data = aioz_api_client.models.response/check_model_is_serving_data.response.CheckModelIsServingData(
                    consumers = 56, 
                    serving = True, ),
                message = '',
                status = 'success'
            )
        else:
            return ResponseCheckModelIsServingResponse(
        )
        """

    def testResponseCheckModelIsServingResponse(self):
        """Test ResponseCheckModelIsServingResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
