# coding: utf-8

"""
    AIOZ-AI-PLATFORM API

    API for AIOZ AI Platform

    The version of the OpenAPI document: 1.0
    Contact: support@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aioz_api_client.models.models_api_key_histories import ModelsApiKeyHistories

class TestModelsApiKeyHistories(unittest.TestCase):
    """ModelsApiKeyHistories unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModelsApiKeyHistories:
        """Test ModelsApiKeyHistories
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModelsApiKeyHistories`
        """
        model = ModelsApiKeyHistories()
        if include_optional:
            return ModelsApiKeyHistories(
                created_at = '',
                model_id = '',
                status = '',
                task_id = '',
                updated_at = ''
            )
        else:
            return ModelsApiKeyHistories(
        )
        """

    def testModelsApiKeyHistories(self):
        """Test ModelsApiKeyHistories"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
