# coding: utf-8

"""
    AIOZ-AI-PLATFORM API

    API for AIOZ AI Platform

    The version of the OpenAPI document: 1.0
    Contact: support@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aioz_api_client.models.response_api_key_info_response import ResponseApiKeyInfoResponse

class TestResponseApiKeyInfoResponse(unittest.TestCase):
    """ResponseApiKeyInfoResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseApiKeyInfoResponse:
        """Test ResponseApiKeyInfoResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseApiKeyInfoResponse`
        """
        model = ResponseApiKeyInfoResponse()
        if include_optional:
            return ResponseApiKeyInfoResponse(
                data = aioz_api_client.models.models/api_key_info.models.ApiKeyInfo(
                    api_price = 1.337, 
                    commit_hash = '', 
                    input_format = { }, 
                    model_description = '', 
                    model_id = '', 
                    output_format = { }, ),
                message = '',
                status = 'success'
            )
        else:
            return ResponseApiKeyInfoResponse(
        )
        """

    def testResponseApiKeyInfoResponse(self):
        """Test ResponseApiKeyInfoResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
