# coding: utf-8

"""
    AIOZ-AI-PLATFORM API

    API for AIOZ AI Platform

    The version of the OpenAPI document: 1.0
    Contact: support@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aioz_api_client.models.response_model_versioning_response import ResponseModelVersioningResponse

class TestResponseModelVersioningResponse(unittest.TestCase):
    """ResponseModelVersioningResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseModelVersioningResponse:
        """Test ResponseModelVersioningResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseModelVersioningResponse`
        """
        model = ResponseModelVersioningResponse()
        if include_optional:
            return ResponseModelVersioningResponse(
                data = aioz_api_client.models.models/model_versioning.models.ModelVersioning(
                    commit_hash = '', 
                    commit_message = '', 
                    created_at = '', 
                    dependency = { }, 
                    id = '', 
                    input_format = { }, 
                    model_id = '', 
                    node_reward = 1.337, 
                    output_format = { }, 
                    platform = '', 
                    sys_require = { }, 
                    test_result = { }, 
                    updated_at = '', 
                    verify_status = '', 
                    verify_task_id = '', ),
                message = '',
                status = 'success'
            )
        else:
            return ResponseModelVersioningResponse(
        )
        """

    def testResponseModelVersioningResponse(self):
        """Test ResponseModelVersioningResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
