# coding: utf-8

"""
    AIOZ-AI-PLATFORM API

    API for AIOZ AI Platform

    The version of the OpenAPI document: 1.0
    Contact: support@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aioz_api_client.models.response_estimate_cost_response import ResponseEstimateCostResponse

class TestResponseEstimateCostResponse(unittest.TestCase):
    """ResponseEstimateCostResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseEstimateCostResponse:
        """Test ResponseEstimateCostResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseEstimateCostResponse`
        """
        model = ResponseEstimateCostResponse()
        if include_optional:
            return ResponseEstimateCostResponse(
                data = aioz_api_client.models.response/estimate_cost_data.response.EstimateCostData(
                    cost = 1.337, 
                    symbol = '$', 
                    unit = 'USD', ),
                message = '',
                status = 'success'
            )
        else:
            return ResponseEstimateCostResponse(
        )
        """

    def testResponseEstimateCostResponse(self):
        """Test ResponseEstimateCostResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
