# coding: utf-8

"""
    AIOZ-AI-PLATFORM API

    API for AIOZ AI Platform

    The version of the OpenAPI document: 1.0
    Contact: support@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aioz_api_client.api.api_key_repository_api import ApiKeyRepositoryApi


class TestApiKeyRepositoryApi(unittest.TestCase):
    """ApiKeyRepositoryApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ApiKeyRepositoryApi()

    def tearDown(self) -> None:
        pass

    def test_api_key_repository_owner_username_repository_name_commit_history_get(self) -> None:
        """Test case for api_key_repository_owner_username_repository_name_commit_history_get

        Get commit history by repository name and branch name by api key
        """
        pass


if __name__ == '__main__':
    unittest.main()
