# coding: utf-8

"""
    AIOZ-AI-PLATFORM API

    API for AIOZ AI Platform

    The version of the OpenAPI document: 1.0
    Contact: support@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aioz_api_client.models.response_check_valid_to_verify_ai_model_response import ResponseCheckValidToVerifyAiModelResponse

class TestResponseCheckValidToVerifyAiModelResponse(unittest.TestCase):
    """ResponseCheckValidToVerifyAiModelResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseCheckValidToVerifyAiModelResponse:
        """Test ResponseCheckValidToVerifyAiModelResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseCheckValidToVerifyAiModelResponse`
        """
        model = ResponseCheckValidToVerifyAiModelResponse()
        if include_optional:
            return ResponseCheckValidToVerifyAiModelResponse(
                data = aioz_api_client.models.response/check_valid_to_verify_ai_model_data.response.CheckValidToVerifyAiModelData(
                    valid = True, ),
                message = '',
                status = 'success'
            )
        else:
            return ResponseCheckValidToVerifyAiModelResponse(
        )
        """

    def testResponseCheckValidToVerifyAiModelResponse(self):
        """Test ResponseCheckValidToVerifyAiModelResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
