# coding: utf-8

"""
    AIOZ-AI-PLATFORM API

    API for AIOZ AI Platform

    The version of the OpenAPI document: 1.0
    Contact: support@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aioz_api_client.models.response_get_task_statistics_data import ResponseGetTaskStatisticsData

class TestResponseGetTaskStatisticsData(unittest.TestCase):
    """ResponseGetTaskStatisticsData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseGetTaskStatisticsData:
        """Test ResponseGetTaskStatisticsData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseGetTaskStatisticsData`
        """
        model = ResponseGetTaskStatisticsData()
        if include_optional:
            return ResponseGetTaskStatisticsData(
                total_cost = 56,
                total_failed = 56,
                total_request = 56,
                total_success = 56
            )
        else:
            return ResponseGetTaskStatisticsData(
        )
        """

    def testResponseGetTaskStatisticsData(self):
        """Test ResponseGetTaskStatisticsData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
