# coding: utf-8

"""
    AIOZ-AI-PLATFORM API

    API for AIOZ AI Platform

    The version of the OpenAPI document: 1.0
    Contact: support@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aioz_api_client.models.models_wallet_with_address import ModelsWalletWithAddress

class TestModelsWalletWithAddress(unittest.TestCase):
    """ModelsWalletWithAddress unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModelsWalletWithAddress:
        """Test ModelsWalletWithAddress
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModelsWalletWithAddress`
        """
        model = ModelsWalletWithAddress()
        if include_optional:
            return ModelsWalletWithAddress(
                balance = 1.337,
                debt = 1.337,
                earnings = 1.337,
                free_balance = 1.337,
                wallet_address = ''
            )
        else:
            return ModelsWalletWithAddress(
        )
        """

    def testModelsWalletWithAddress(self):
        """Test ModelsWalletWithAddress"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
