# coding: utf-8

"""
    AIOZ-AI-PLATFORM API

    API for AIOZ AI Platform

    The version of the OpenAPI document: 1.0
    Contact: support@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aioz_api_client.models.models_api_key_info import ModelsApiKeyInfo

class TestModelsApiKeyInfo(unittest.TestCase):
    """ModelsApiKeyInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModelsApiKeyInfo:
        """Test ModelsApiKeyInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModelsApiKeyInfo`
        """
        model = ModelsApiKeyInfo()
        if include_optional:
            return ModelsApiKeyInfo(
                api_price = 1.337,
                commit_hash = '',
                input_format = { },
                model_description = '',
                model_id = '',
                output_format = { }
            )
        else:
            return ModelsApiKeyInfo(
        )
        """

    def testModelsApiKeyInfo(self):
        """Test ModelsApiKeyInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
