# coding: utf-8

"""
    AIOZ-AI-PLATFORM API

    API for AIOZ AI Platform

    The version of the OpenAPI document: 1.0
    Contact: support@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aioz_api_client.api.api_key_model_verify_api import ApiKeyModelVerifyApi


class TestApiKeyModelVerifyApi(unittest.TestCase):
    """ApiKeyModelVerifyApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ApiKeyModelVerifyApi()

    def tearDown(self) -> None:
        pass

    def test_api_key_model_id_pre_verify_post(self) -> None:
        """Test case for api_key_model_id_pre_verify_post

        Check Valid Source code To Verify Ai Model By Api Key
        """
        pass

    def test_api_key_model_id_verify_cost_post(self) -> None:
        """Test case for api_key_model_id_verify_cost_post

        Calculate Cost To Verify Ai Model By Api Key
        """
        pass

    def test_api_key_model_id_verify_post(self) -> None:
        """Test case for api_key_model_id_verify_post

        Verify Ai Model By Api Key
        """
        pass

    def test_api_key_model_id_verify_task_get(self) -> None:
        """Test case for api_key_model_id_verify_task_get

        Get List Verify Model Task By Commit Hash And Status
        """
        pass

    def test_api_key_model_verify_hub_task_id_get(self) -> None:
        """Test case for api_key_model_verify_hub_task_id_get

        Get Model Versioning By Hub Task Id By Api Key
        """
        pass

    def test_api_key_model_verify_platform_task_id_get(self) -> None:
        """Test case for api_key_model_verify_platform_task_id_get

        Get Verify Platform Task By Id By Api Key
        """
        pass


if __name__ == '__main__':
    unittest.main()
