# coding: utf-8

"""
    AIOZ-AI-PLATFORM API

    API for AIOZ AI Platform

    The version of the OpenAPI document: 1.0
    Contact: support@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aioz_api_client.models.request_calculate_cost_to_verify_ai_model_request import RequestCalculateCostToVerifyAiModelRequest

class TestRequestCalculateCostToVerifyAiModelRequest(unittest.TestCase):
    """RequestCalculateCostToVerifyAiModelRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestCalculateCostToVerifyAiModelRequest:
        """Test RequestCalculateCostToVerifyAiModelRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestCalculateCostToVerifyAiModelRequest`
        """
        model = RequestCalculateCostToVerifyAiModelRequest()
        if include_optional:
            return RequestCalculateCostToVerifyAiModelRequest(
                commit_hash = '',
                platforms = [
                    ''
                    ]
            )
        else:
            return RequestCalculateCostToVerifyAiModelRequest(
                commit_hash = '',
                platforms = [
                    ''
                    ],
        )
        """

    def testRequestCalculateCostToVerifyAiModelRequest(self):
        """Test RequestCalculateCostToVerifyAiModelRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
