# coding: utf-8

"""
    AIOZ-AI-PLATFORM API

    API for AIOZ AI Platform

    The version of the OpenAPI document: 1.0
    Contact: support@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aioz_api_client.models.response_get_task_statistics_response import ResponseGetTaskStatisticsResponse

class TestResponseGetTaskStatisticsResponse(unittest.TestCase):
    """ResponseGetTaskStatisticsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseGetTaskStatisticsResponse:
        """Test ResponseGetTaskStatisticsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseGetTaskStatisticsResponse`
        """
        model = ResponseGetTaskStatisticsResponse()
        if include_optional:
            return ResponseGetTaskStatisticsResponse(
                data = aioz_api_client.models.response/get_task_statistics_data.response.GetTaskStatisticsData(
                    total_cost = 56, 
                    total_failed = 56, 
                    total_request = 56, 
                    total_success = 56, ),
                message = '',
                status = 'success'
            )
        else:
            return ResponseGetTaskStatisticsResponse(
        )
        """

    def testResponseGetTaskStatisticsResponse(self):
        """Test ResponseGetTaskStatisticsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
