# coding: utf-8

"""
    AIOZ-AI-PLATFORM API

    API for AIOZ AI Platform

    The version of the OpenAPI document: 1.0
    Contact: support@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aioz_api_client.models.response_wallet_with_address_response import ResponseWalletWithAddressResponse

class TestResponseWalletWithAddressResponse(unittest.TestCase):
    """ResponseWalletWithAddressResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseWalletWithAddressResponse:
        """Test ResponseWalletWithAddressResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseWalletWithAddressResponse`
        """
        model = ResponseWalletWithAddressResponse()
        if include_optional:
            return ResponseWalletWithAddressResponse(
                data = aioz_api_client.models.models/wallet_with_address.models.WalletWithAddress(
                    balance = 1.337, 
                    debt = 1.337, 
                    earnings = 1.337, 
                    free_balance = 1.337, 
                    wallet_address = '', ),
                message = '',
                status = 'success'
            )
        else:
            return ResponseWalletWithAddressResponse(
        )
        """

    def testResponseWalletWithAddressResponse(self):
        """Test ResponseWalletWithAddressResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
