# coding: utf-8

"""
    AIOZ-AI-PLATFORM API

    API for AIOZ AI Platform

    The version of the OpenAPI document: 1.0
    Contact: support@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aioz_api_client.models.models_model_versioning import ModelsModelVersioning

class TestModelsModelVersioning(unittest.TestCase):
    """ModelsModelVersioning unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModelsModelVersioning:
        """Test ModelsModelVersioning
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModelsModelVersioning`
        """
        model = ModelsModelVersioning()
        if include_optional:
            return ModelsModelVersioning(
                commit_hash = '',
                commit_message = '',
                created_at = '',
                dependency = { },
                id = '',
                input_format = { },
                model_id = '',
                node_reward = 1.337,
                output_format = { },
                platform = '',
                sys_require = { },
                test_result = { },
                updated_at = '',
                verify_status = '',
                verify_task_id = ''
            )
        else:
            return ModelsModelVersioning(
        )
        """

    def testModelsModelVersioning(self):
        """Test ModelsModelVersioning"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
