# coding: utf-8

"""
    AIOZ-AI-PLATFORM API

    API for AIOZ AI Platform

    The version of the OpenAPI document: 1.0
    Contact: support@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aioz_api_client.api.api_key_model_versioning_api import ApiKeyModelVersioningApi


class TestApiKeyModelVersioningApi(unittest.TestCase):
    """ApiKeyModelVersioningApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ApiKeyModelVersioningApi()

    def tearDown(self) -> None:
        pass

    def test_api_key_model_id_versioning_delete(self) -> None:
        """Test case for api_key_model_id_versioning_delete

        Delete Model Versioning By Commit Hash By Api Key
        """
        pass

    def test_api_key_model_id_versioning_get(self) -> None:
        """Test case for api_key_model_id_versioning_get

        Get Current Model Versioning By Model Id By ApiKey
        """
        pass

    def test_api_key_model_id_versioning_list_get(self) -> None:
        """Test case for api_key_model_id_versioning_list_get

        Get Verified List Model Versioning By Api Key
        """
        pass

    def test_api_key_model_id_versioning_put(self) -> None:
        """Test case for api_key_model_id_versioning_put

        Change Model Versioning By Commit Hash By Api Key
        """
        pass


if __name__ == '__main__':
    unittest.main()
