# coding: utf-8

"""
    AIOZ-AI-PLATFORM API

    API for AIOZ AI Platform

    The version of the OpenAPI document: 1.0
    Contact: support@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aioz_api_client.models.response_get_api_key_permission_data import ResponseGetApiKeyPermissionData

class TestResponseGetApiKeyPermissionData(unittest.TestCase):
    """ResponseGetApiKeyPermissionData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseGetApiKeyPermissionData:
        """Test ResponseGetApiKeyPermissionData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseGetApiKeyPermissionData`
        """
        model = ResponseGetApiKeyPermissionData()
        if include_optional:
            return ResponseGetApiKeyPermissionData(
                api_key_packages = [
                    aioz_api_client.models.models/api_key_package.models.ApiKeyPackage(
                        model_id = '', 
                        uses_remaining = 56, )
                    ],
                limit_models = True,
                models = [
                    ''
                    ]
            )
        else:
            return ResponseGetApiKeyPermissionData(
        )
        """

    def testResponseGetApiKeyPermissionData(self):
        """Test ResponseGetApiKeyPermissionData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
