# coding: utf-8

"""
    AIOZ-AI-PLATFORM API

    API for AIOZ AI Platform

    The version of the OpenAPI document: 1.0
    Contact: support@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aioz_api_client.models.models_platform_task import ModelsPlatformTask

class TestModelsPlatformTask(unittest.TestCase):
    """ModelsPlatformTask unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModelsPlatformTask:
        """Test ModelsPlatformTask
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModelsPlatformTask`
        """
        model = ModelsPlatformTask()
        if include_optional:
            return ModelsPlatformTask(
                platform = '',
                test_result = { },
                updated_at = '',
                verify_task_id = ''
            )
        else:
            return ModelsPlatformTask(
        )
        """

    def testModelsPlatformTask(self):
        """Test ModelsPlatformTask"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
