# coding: utf-8

"""
    AIOZ-AI-PLATFORM API

    API for AIOZ AI Platform

    The version of the OpenAPI document: 1.0
    Contact: support@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aioz_api_client.api.api_key_model_api import ApiKeyModelApi


class TestApiKeyModelApi(unittest.TestCase):
    """ApiKeyModelApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ApiKeyModelApi()

    def tearDown(self) -> None:
        pass

    def test_api_key_model_id_info_get(self) -> None:
        """Test case for api_key_model_id_info_get

        Get Api Key Model Info
        """
        pass

    def test_api_key_model_id_serving_get(self) -> None:
        """Test case for api_key_model_id_serving_get

        Check Model Is Serving
        """
        pass

    def test_api_key_model_id_statistics_post(self) -> None:
        """Test case for api_key_model_id_statistics_post

        Get Model Statistics
        """
        pass

    def test_api_key_model_id_task_cost_get(self) -> None:
        """Test case for api_key_model_id_task_cost_get

        Get cost to compute task by model api key
        """
        pass

    def test_api_key_model_verify_support_platforms_get(self) -> None:
        """Test case for api_key_model_verify_support_platforms_get

        Get List Platforms Support By Api Key
        """
        pass


if __name__ == '__main__':
    unittest.main()
