# coding: utf-8

"""
    AIOZ-AI-PLATFORM API

    API for AIOZ AI Platform

    The version of the OpenAPI document: 1.0
    Contact: support@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aioz_api_client.models.request_get_api_key_statistics_by_model_id_request import RequestGetApiKeyStatisticsByModelIdRequest

class TestRequestGetApiKeyStatisticsByModelIdRequest(unittest.TestCase):
    """RequestGetApiKeyStatisticsByModelIdRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestGetApiKeyStatisticsByModelIdRequest:
        """Test RequestGetApiKeyStatisticsByModelIdRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestGetApiKeyStatisticsByModelIdRequest`
        """
        model = RequestGetApiKeyStatisticsByModelIdRequest()
        if include_optional:
            return RequestGetApiKeyStatisticsByModelIdRequest(
                var_from = '2023-05-07 15:04:05',
                to = '2023-05-07 15:04:05'
            )
        else:
            return RequestGetApiKeyStatisticsByModelIdRequest(
        )
        """

    def testRequestGetApiKeyStatisticsByModelIdRequest(self):
        """Test RequestGetApiKeyStatisticsByModelIdRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
