# coding: utf-8

"""
    AIOZ-AI-PLATFORM API

    API for AIOZ AI Platform

    The version of the OpenAPI document: 1.0
    Contact: support@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aioz_api_client.models.models_follow import ModelsFollow

class TestModelsFollow(unittest.TestCase):
    """ModelsFollow unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModelsFollow:
        """Test ModelsFollow
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModelsFollow`
        """
        model = ModelsFollow()
        if include_optional:
            return ModelsFollow(
                avatar = '',
                id = '',
                name = '',
                username = ''
            )
        else:
            return ModelsFollow(
        )
        """

    def testModelsFollow(self):
        """Test ModelsFollow"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
