# coding: utf-8

"""
    AIOZ-AI-PLATFORM API

    API for AIOZ AI Platform

    The version of the OpenAPI document: 1.0
    Contact: support@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aioz_api_client.api.api_key_api import ApiKeyApi


class TestApiKeyApi(unittest.TestCase):
    """ApiKeyApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ApiKeyApi()

    def tearDown(self) -> None:
        pass

    def test_api_key_balance_get(self) -> None:
        """Test case for api_key_balance_get

        Get Api Key Balance
        """
        pass

    def test_api_key_permission_get(self) -> None:
        """Test case for api_key_permission_get

        Get Api Key Permission
        """
        pass

    def test_api_key_statistics_post(self) -> None:
        """Test case for api_key_statistics_post

        Get Api Key Statistics
        """
        pass

    def test_api_key_task_histories_get(self) -> None:
        """Test case for api_key_task_histories_get

        Get Tasks Histories
        """
        pass

    def test_api_key_task_id_cancel_delete(self) -> None:
        """Test case for api_key_task_id_cancel_delete

        Cancel Task By Api Key
        """
        pass

    def test_api_key_task_id_result_get(self) -> None:
        """Test case for api_key_task_id_result_get

        Get Task Result
        """
        pass

    def test_api_key_task_post(self) -> None:
        """Test case for api_key_task_post

        Distribute Task (Api-Key)
        """
        pass


if __name__ == '__main__':
    unittest.main()
