# coding: utf-8

"""
    AIOZ-AI-PLATFORM API

    API for AIOZ AI Platform

    The version of the OpenAPI document: 1.0
    Contact: support@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aioz_api_client.models.request_distribute_task_request import RequestDistributeTaskRequest

class TestRequestDistributeTaskRequest(unittest.TestCase):
    """RequestDistributeTaskRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestDistributeTaskRequest:
        """Test RequestDistributeTaskRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestDistributeTaskRequest`
        """
        model = RequestDistributeTaskRequest()
        if include_optional:
            return RequestDistributeTaskRequest(
                files = [
                    None
                    ],
                input_params = { },
                model_id = ''
            )
        else:
            return RequestDistributeTaskRequest(
        )
        """

    def testRequestDistributeTaskRequest(self):
        """Test RequestDistributeTaskRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
